<?php

namespace App\Filament\Widgets;

use App\Models\Lead;
use App\Models\Scan;
use App\Models\ScanResult;
use Filament\Widgets\StatsOverviewWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;

class QsaStatsOverview extends StatsOverviewWidget
{
    protected function getStats(): array
    {
        $timezone = config('app.timezone', 'Asia/Kolkata');
        $todayStart = now($timezone)->startOfDay();
        $todayEnd = $todayStart->copy()->endOfDay();

        $liveScansQuery = Scan::query()->whereNull('legacy_source');
        $legacyScansQuery = Scan::query()->whereNotNull('legacy_source');
        $averageVisibilityScore = (int) round(
            ScanResult::query()
                ->whereHas('scan', fn ($query) => $query->whereNull('legacy_source'))
                ->avg('score') ?? 0
        );

        return [
            Stat::make('Live QSA Scans', (clone $liveScansQuery)->count())
                ->description('Current scans generated by the Laravel QSA platform.'),
            Stat::make('Legacy Archived Scans', (clone $legacyScansQuery)->count())
                ->description('Legacy archive contains old scans preserved from previous .NET QSA.'),
            Stat::make('Total Scan Records', Scan::query()->count())
                ->description('Live scans plus archived legacy scan history.'),
            Stat::make('Total Leads', Lead::query()->count()),
            Stat::make('Average Visibility Score', $averageVisibilityScore.'/100')
                ->description('Live QSA scans only. Legacy archived scans are excluded.'),
            Stat::make('Scans Today', (clone $liveScansQuery)->whereBetween('created_at', [$todayStart, $todayEnd])->count())
                ->description('Live QSA scans only.'),
            Stat::make('Leads Today', Lead::query()->whereBetween('created_at', [$todayStart, $todayEnd])->count()),
        ];
    }
}
