<?php

namespace App\Http\Controllers;

use App\Models\Company;
use App\Models\Scan;
use App\Services\Reports\ReportDataBuilder;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class PublicReportPdfController
{
    public function show(Request $request, Scan $scan, ReportDataBuilder $reportDataBuilder): View
    {
        $scan->load('result');

        $reportData = $reportDataBuilder->build($scan);

        $company = new Company([
            'name' => 'Quick SEO Analysis',
            'website_url' => config('app.url'),
            'primary_color' => '#1d4ed8',
            'contact_email' => null,
            'white_label_settings' => [
                'report_footer_text' => 'Visibility report generated by Quick SEO Analysis.',
            ],
        ]);

        return view('reports.pdf.white-label', [
            'scan' => $scan,
            'result' => $scan->result,
            'company' => $company,
            'whiteLabelActive' => false,
            'reportData' => $reportData,
            'backUrl' => route('report.show', ['scan' => $scan->uuid]),
        ]);
    }
}
